### ISSUE TITLE
Intellisense not working for BigQuery functions

### ISSUE THREAD

**Issue by mattwelke** [dr666m1/bq-extension-vscode#15]
Not sure if this is a bug or lack of feature right now, since I see the extension is considered alpha right now. Feel free to categorize appropriately.

I tried to write some BigQuery SQL. I wasn't able to use info related to my datasets and tables (see https://github.com/dr666m1/bq-extension-vscode/issues/14 for details), but I was able to get syntax highlighting and function autocompletion working well. It helped me type "ABS" in this example but moving my cursor over it didn't tell me what ABS did. I'd have to consult the docs online:

![vscode_bq_no_autocomplete](https://user-images.githubusercontent.com/7719209/139600544-fd45ccdc-263e-431e-ba88-74004a886db2.gif)

Expected behavior: When moving my cursor over ABS, it would display information about the function like its parameters, the function description, maybe the description in the BQ online docs, etc.

System details:

OS: WSL 2 (Ubuntu)
VS Code version:
```
Version: 1.61.2 (user setup)
Commit: 6cba118ac49a1b88332f312a8f67186f7f3c1643
Date: 2021-10-19T14:57:20.575Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043
```
Extension version: v1.9.0

**Comment by dr666m1** [comment]
That is simply a lack of feature,
but I'm planning to work on it when I have time.

**Comment by dr666m1** [comment]
Version `0.0.13` displays the example of each function.
 
![hover](https://user-images.githubusercontent.com/26474260/148054027-62760465-1412-4e16-b9e8-b8d7131a7454.gif)
