### ISSUE TITLE
updateCache is not working about datasets in several locations

### ISSUE THREAD

**Issue by a24k** [dr666m1/bq-extension-vscode#38]
I'm using your LSP server with nvim-lsp environment ([see my article written in japanese](https://zenn.dev/a24k/articles/a8b882019da106)).

I'm trying to use `bq/updateCache` with my BigQuery projects, but sometime it's not work.
I think it is caused by location of the dataset, because there are no problem with datasets located US.
A query about `INFORMATION_SCHEMA.SCHEMATA` might respond only about location where the job runs.

Instead of the query, for example, we can use `bq` command with following parameters.

```
bq ls -d --project_id=<project_id> --format=json
```

Thanks, for great product.

**Comment by dr666m1** [comment]
Thank you for your bug report.

週末にでもゆっくり確認させていただきますね。

**Comment by dr666m1** [comment]
> Instead of the query, for example, we can use `bq` command with following parameters.

That's a good idea.

I have just published new version (0.0.17).
If it does not work fine, please feel free to reopen the issue.

**Comment by a24k** [comment]
Thank you for the response.

As you can imagine, I have some datasets in `US` and `asia-northeast1`.
And it (0.0.17) is works great in my environment.

早々のご対応ありがとうございました。しかも、cache のスキーマ変更まで。
上手く動作しており、ますますクエリがはかどりそうです。
