### ISSUE TITLE
onLanguage:bigquery does not activate code completion

### ISSUE THREAD

**Issue by timandersonmixcloud** [dr666m1/bq-extension-vscode#40]
If you open a new file and choose language as bigquery the extension does not suggest table names etc. You have to save the file as .bq or .bigquery to get it to work.

**Comment by dr666m1** [comment]
Thanks for your bug report.
I found a solution (I have to change [DocumentFilter](https://code.visualstudio.com/api/references/vscode-api#DocumentFilter) setting).
This issue will be fixed in the next release.

**Comment by dr666m1** [comment]
I have just published new version (0.0.17).
If it does not work, please feel free to reopen the issue.

**Comment by timandersonmixcloud** [comment]
This works perfectly! Thank you so much for fixing this so quickly.
