### ISSUE TITLE
ProjectId and DatasetId must be non-empty

### ISSUE THREAD

**Issue by GabrielCarvalhoCVER** [dr666m1/bq-extension-vscode#73]
For some reason it keeps saying that the ProjectId and datasetid is empty. 

![image](https://user-images.githubusercontent.com/87732527/179833320-b8780b72-776d-4b96-94e9-4733302a7785.png)

**Comment by GabrielCarvalhoCVER** [comment]
Oh, and most likely for the same reason the table name suggestion does not appear. 

![image](https://user-images.githubusercontent.com/87732527/179839564-23838cf3-3c5c-4948-9d2f-71c46e529863.png)

![image](https://user-images.githubusercontent.com/87732527/179839779-844840a3-d79f-4629-84c9-2992cef4c72a.png)

By the way, thank you very much for the extension! =]

**Comment by dr666m1** [comment]
This extension depends on this  [client library](https://github.com/googleapis/nodejs-bigquery). Does it work properly?
Try these commands.

```bash
mkdir temp
cd temp
npm init -y
npm install @google-cloud/bigquery
echo '
const {BigQuery} = require("@google-cloud/bigquery");
async function execDryRun() {
  const bigqueryClient = new BigQuery();
  const [job] = await bigqueryClient.createQueryJob({
    query: "select 1",
    dryRun: true,
  });
  console.log("done!");
}
execDryRun();
' > index.js
node index.js
```
If you see the same error, there may be something wrong with your setup.
